### ISSUE TITLE
Long latency on every navigation click

### ISSUE THREAD

**Issue by paulirish** [developerhub-io/developerhub-io#1]
Trying out the demo app I noticed clicking on each link shows a skeleton screen immediately, but the wait for content was quite long. 

I profiled it and see that its ~400ms. Ideally this is under 100ms.

It's due to the CORS request to api.developerhub.. And two requests are required, the preflight and then the real one.

![image](https://user-images.githubusercontent.com/39191/45399620-a25a9980-b5fd-11e8-932b-eb1ace096bc3.png)

~160ms for each response is pretty high for the API server. That could probably be reduced. 

Still, incurring a preflight everytime is a shame. I'm not sure why it's there.. Perhaps because of the Authorization header?

![image](https://user-images.githubusercontent.com/39191/45399714-f8c7d800-b5fd-11e8-94b1-02a1251f066b.png)

goodluck!

**Comment by zaiddabaeen** [comment]
Hey Paul! Thank you for your comments here. I've read some of your Medium posts already ;)
That's mostly due to the fact that our servers are in Ireland not in the US. The average response I am getting here being in London is ~150ms at the moment (using my home crappy internet connection hah).

Regardless, we will be moving our servers to the US soon, and work on further speed ups!
